# -*- coding: UTF-8 -*-
# generated by wxGlade 0.3.5.1 on Thu Mar 24 15:40:42 2005
#
# File: $Id$
#
# Eruditor (ērudītor), a card-based vocabulary training program
# Copyright (C) 2005 Alexander Lee
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import wx

import Config
import Card

from Globals import *

# begin wxGlade: dependencies
# end wxGlade

class AddDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # Get a custom arg and remove from kwds dict.
        # FIXME see PropertiesDialog.py
        self.lesson = kwds["lesson"]
        del kwds["lesson"]
        self.parent = args[0]

        # begin wxGlade: AddDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.labelFront = wx.StaticText(self, -1, "Front")
        self.textFront = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelMiddle = wx.StaticText(self, -1, "Middle")
        self.textMiddle = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelBack = wx.StaticText(self, -1, "Back")
        self.textBack = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelSection = wx.StaticText(self, -1, "Section")
        self.textSection = wx.TextCtrl(self, -1, "")
        self.buttonAdd = wx.Button(self, wx.ID_ADD, "Add")
        self.buttonClose = wx.Button(self, wx.ID_CLOSE, "Close")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        font = Config.GetTextFont()
        self.textFront.SetFont(font)
        self.textMiddle.SetFont(font)
        self.textBack.SetFont(font)

        self.Bind(wx.EVT_BUTTON, self.OnButtonAdd, self.buttonAdd)
        self.Bind(wx.EVT_BUTTON, self.OnButtonClose, self.buttonClose)

    def __set_properties(self):
        # begin wxGlade: AddDialog.__set_properties
        self.SetTitle("Add Card")
        self.labelFront.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textFront.SetSize((300,60))
        self.labelMiddle.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textMiddle.SetSize((300,60))
        self.labelBack.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textBack.SetSize((300,60))
        self.labelSection.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textSection.SetSize((300, 30))
        self.buttonAdd.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddDialog.__do_layout
        sizerCardAdd = wx.BoxSizer(wx.VERTICAL)
        sizerButtons = wx.BoxSizer(wx.HORIZONTAL)
        sizerCardAdd.Add(self.labelFront, 0, wx.LEFT|wx.TOP|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.textFront, 2, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.labelMiddle, 0, wx.LEFT|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.textMiddle, 2, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.labelBack, 0, wx.LEFT|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.textBack, 2, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.labelSection, 0, wx.LEFT|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(self.textSection, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerButtons.Add((20, 20), 1, wx.FIXED_MINSIZE, 0)
        sizerButtons.Add(self.buttonAdd, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizerButtons.Add(self.buttonClose, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizerCardAdd.Add(sizerButtons, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizerCardAdd)
        sizerCardAdd.Fit(self)
        sizerCardAdd.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def OnButtonAdd(self, event):
        ftxt = self.textFront.GetValue().strip()
        mtxt = self.textMiddle.GetValue().strip()
        btxt = self.textBack.GetValue().strip()
        sectxt = self.textSection.GetValue().strip()

        if ftxt == "":
            dlg = wx.MessageDialog(self,
                    "You need to supply a headword for the card.",
                    "Whoops!", wx.OK)
            try: dlg.ShowModal()
            finally: dlg.Destroy()
        
        else:
            card = Card.Card(self.lesson.type,
                    ftxt, None, 0, mtxt, None, 0, btxt, None, 0,
                    sectxt)
            self.lesson.AddCard(card)

            self.textFront.SetValue("")
            self.textMiddle.SetValue("")
            self.textBack.SetValue("")

            self.parent.pilesPanel.Update(self.parent.lesson)

        self.textFront.SetFocus()

    def OnButtonClose(self, event):
        self.EndModal(wx.ID_CLOSE)

# end of class AddDialog


