# -*- coding: UTF-8 -*-
# generated by wxGlade 0.3.5.1 on Wed Mar 23 02:11:25 2005
#
# Eruditor (ērudītor), a card-based vocabulary training program
# Copyright (C) 2005 Alexander Lee
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import wx

from Globals import *

# begin wxGlade: dependencies
# end wxGlade

class EditDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # Get a custom arg and remove from kwds dict.
        # FIXME see PropertiesDialog.py
        self.card = kwds["card"]
        del kwds["card"]

        # begin wxGlade: EditDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.labelFront = wx.StaticText(self, -1, "Front")
        self.textFront = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelMiddle = wx.StaticText(self, -1, "Middle")
        self.textMiddle = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelBack = wx.StaticText(self, -1, "Back")
        self.textBack = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.labelSection = wx.StaticText(self, -1, "Section")
        self.textSection = wx.TextCtrl(self, -1, "")
        self.buttonOk = wx.Button(self, wx.ID_OK, "OK")
        self.buttonCancel = wx.Button(self, wx.ID_CANCEL, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self._Populate()
        self.Bind(wx.EVT_BUTTON, self.OnButtonOk, self.buttonOk)
        self.Bind(wx.EVT_BUTTON, self.OnButtonCancel, self.buttonCancel)

    def __set_properties(self):
        # begin wxGlade: EditDialog.__set_properties
        self.SetTitle("Edit Card")
        self.labelFront.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textFront.SetSize((300,60))
        self.labelMiddle.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textMiddle.SetSize((300,60))
        self.labelBack.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.textBack.SetSize((300,60))
        self.labelSection.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.buttonOk.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EditDialog.__do_layout
        sizerCardEdit = wx.BoxSizer(wx.VERTICAL)
        sizerButtons = wx.BoxSizer(wx.HORIZONTAL)
        sizerCardEdit.Add(self.labelFront, 0, wx.LEFT|wx.TOP|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.textFront, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.labelMiddle, 0, wx.LEFT|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.textMiddle, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.labelBack, 0, wx.LEFT|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.textBack, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.labelSection, 0, wx.LEFT|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(self.textSection, 0, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizerButtons.Add((20, 20), 1, wx.FIXED_MINSIZE, 0)
        sizerButtons.Add(self.buttonOk, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizerButtons.Add(self.buttonCancel, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizerCardEdit.Add(sizerButtons, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizerCardEdit)
        sizerCardEdit.Fit(self)
        sizerCardEdit.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def _Populate(self):
        self.textFront.SetValue(self.card.GetTextRaw(FRONT))
        self.textMiddle.SetValue(self.card.GetTextRaw(MIDDLE))
        self.textBack.SetValue(self.card.GetTextRaw(BACK))
        self.textSection.SetValue(self.card.section)

    def OnButtonOk(self, event):
        self.card.SetText(FRONT, self.textFront.GetValue().strip())
        self.card.SetText(MIDDLE, self.textMiddle.GetValue().strip())
        self.card.SetText(BACK, self.textBack.GetValue().strip())
        self.card.section = self.textSection.GetValue().strip()
        event.Skip()

    def OnButtonCancel(self, event):
        event.Skip()

# end of class EditDialog

