#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.3.5.1 on Sat Mar 19 16:28:47 2005
#
# Eruditor (ērudītor), a card-based vocabulary training program
# Copyright (C) 2005 Alexander Lee
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import sys
import wx
from MainFrame import MainFrame
import Config

class Eruditor(wx.App):
    def __init__(self, filename):
        wx.App.__init__(self)
        self.filename = filename

    def OnInit(self):
        if len(sys.argv) == 2: filename = sys.argv[1]
        else: filename = None
        Config.Initialize() # Set up the config module

        wx.InitAllImageHandlers()
        mainFrame = MainFrame(None, -1, filename=filename)
        self.SetTopWindow(mainFrame)
        mainFrame.Show()
        return 1

# end of class Eruditor

if __name__ == "__main__":
    if len(sys.argv) > 2:
        print """Usage: python Eruditor.py [FILE]
A vocabulary training program.

The optional FILE argument is the lesson to load.
With no FILE, a blank lesson is loaded.

Report bugs to <alexanderlee@users.berlios.de>."""
        sys.exit(0)

    Eruditor = Eruditor(0)
    Eruditor.MainLoop()
