# -*- coding: UTF-8 -*-
# generated by wxGlade 0.3.5.1 on Sun Mar 20 13:41:16 2005
#
# File: $Id$
#
# Eruditor (ērudītor), a card-based vocabulary training program
# Copyright (C) 2005 Alexander Lee
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import wx

import Config

# begin wxGlade: dependencies
# end wxGlade

class PreferencesDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PreferencesDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.prefsHeader = wx.StaticText(self, -1, "Preferences")
        self.textTextFont = wx.StaticText(self, -1, "Card text font:")
        self.buttonTextFont = wx.Button(self, wx.NewId(), "Select ...")
        self.textListFont = wx.StaticText(self, -1, "List text font:")
        self.buttonListFont = wx.Button(self, wx.NewId(), "Select ...")
        self.buttonClose = wx.Button(self, wx.ID_CLOSE, "Close")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.Bind(wx.EVT_BUTTON, self.OnButtonTextFont, self.buttonTextFont)
        self.Bind(wx.EVT_BUTTON, self.OnButtonListFont, self.buttonListFont)
        self.Bind(wx.EVT_BUTTON, self.OnButtonClose, self.buttonClose)

    def __set_properties(self):
        # begin wxGlade: PreferencesDialog.__set_properties
        self.SetTitle("Preferences")
        self.prefsHeader.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PreferencesDialog.__do_layout
        sizerVert = wx.BoxSizer(wx.VERTICAL)
        sizerButtons = wx.BoxSizer(wx.HORIZONTAL)
        sizerGrid = wx.FlexGridSizer(2, 2, 10, 10)
        sizerVert.Add(self.prefsHeader, 0, wx.ALL|wx.FIXED_MINSIZE, 10)
        sizerGrid.Add(self.textTextFont, 1, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.FIXED_MINSIZE, 5)
        sizerGrid.Add(self.buttonTextFont, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizerGrid.Add(self.textListFont, 1, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.FIXED_MINSIZE, 5)
        sizerGrid.Add(self.buttonListFont, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizerVert.Add(sizerGrid, 1, wx.ALL|wx.EXPAND, 10)
        sizerButtons.Add((20, 20), 1, wx.FIXED_MINSIZE, 0)
        sizerButtons.Add(self.buttonClose, 0, wx.FIXED_MINSIZE, 10)
        sizerVert.Add(sizerButtons, 0, wx.ALL|wx.EXPAND, 10)
        self.SetAutoLayout(True)
        self.SetSizer(sizerVert)
        sizerVert.Fit(self)
        sizerVert.SetSizeHints(self)
        self.Layout()
        # end wxGlade

        self.sizerVert = sizerVert
        self.sizerGrid = sizerGrid

    def OnButtonTextFont(self, event):
        fdata = wx.FontData()
        fdata.SetInitialFont(Config.GetTextFont())
        dlg = wx.FontDialog(self, fdata)
        try:
            if dlg.ShowModal() == wx.ID_OK:
                fdata = dlg.GetFontData()
                font = fdata.GetChosenFont()
                Config.SetTextFont(font.GetFaceName(),
                        font.GetStyle(),
                        font.GetWeight(),
                        font.GetPointSize())
        finally:
            dlg.Destroy()

    def OnButtonListFont(self, event):
        fdata = wx.FontData()
        fdata.SetInitialFont(Config.GetListFont())
        dlg = wx.FontDialog(self, fdata)
        try:
            if dlg.ShowModal() == wx.ID_OK:
                fdata = dlg.GetFontData()
                font = fdata.GetChosenFont()
                Config.SetListFont(font.GetFaceName(),
                        font.GetStyle(),
                        font.GetWeight(),
                        font.GetPointSize())
        finally:
            dlg.Destroy()

    def OnButtonClose(self, event):
        self.EndModal(wx.ID_CLOSE)

# end of class PreferencesDialog


